[app]
type="sender"

[logger]
level = "DEBUG"

[storage]
type = "DB"
host = "pg"
port = "5432"
user = "postgres"
password = "postgres"
dbname = "events_db"
sslmode = "disable"

[http]
host = "127.0.0.1"
port = "8090"

[grpc]
host = "calendar"
port = "50051"

[rabbit]
user = "admin"
password = "admin"
host =  "rabbitmq"
port = "5672"