[app]
type = "main"

[logger]
level = "DEBUG"

[storage]
type = "DB"
host = "pg"
port = "5432"
user = "postgres"
password = "postgres"
dbname = "events_db"
sslmode = "disable"

[http]
host = ""
port = "8080"

[grpc]
host = ""
port = "50051"
